### ISSUE TITLE
Required packages could not be built

### ISSUE THREAD

**Issue by SamanthaNicole** [biobakery/homebrew-biobakery#10]
Hello,

I'm trying to install Lefse using Homebrew and I get this error at the end:

> ============================================================================
>                         * The following required packages can not be built:
>                         * freetype, png
> 
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
> https://github.com/biobakery/homebrew-biobakery/issues

I then used brew to install freetype (which completed successfully), but when I ran the brew install for lefse again I got the same error except png is no longer a problem.  It is only freetype.  My brew is up to date, so I'm unsure what the issue is.

Any help on getting this lefse install working would be greatly appreciated!

Thanks,
Samantha

**Comment by ljmciver** [comment]
Hi Samantha - Sometimes freetype is installed (by brew or another package manager) in a location that is not picked up by matplotlib (a dependency for lefse). Would you try the recommendation in the README FAQ number 4? I think this should resolve your issue. Alternatively we host Docker images for all biobakery tools including lefse. These have all dependencies installed if you would prefer. Please reopen this issue if you continue to have errors with dependencies.

Thanks!
Lauren
