### ISSUE TITLE
Errors with installing lefse

### ISSUE THREAD

**Issue by mengwu1002** [biobakery/homebrew-biobakery#12]
Hi,

I tried to homebrew to install lefse, got error messages as
Last 15 lines from /Users/mengwu/Library/Logs/Homebrew/lefse/02.python:
                 cairo: no  [cairocffi or pycairo not found]
             windowing: no  [Microsoft Windows only]

OPTIONAL LATEX DEPENDENCIES
                dvipng: no
           ghostscript: no
                 latex: no
               pdftops: no

OPTIONAL PACKAGE DATA
                  dlls: no  [skipping due to configuration]

============================================================================
                        * The following required packages can not be built:
                        * freetype, png

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/biobakery/homebrew-biobakery/issues

Error: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

Could you please help.

Thanks,
Meng

**Comment by ljmciver** [comment]
Hello Meng - Can you try installing png and freetype with homebrew?
$ brew install png
$ brew install freetype

If that does not work, sometimes freetype is installed (by brew or another package manager) in a location that is not picked up by matplotlib (a dependency for lefse). Would you try the recommendation in the README FAQ number 4? I think this should resolve your issue. Alternatively we host Docker images for all biobakery tools including lefse. These have all dependencies installed if you would prefer. Please reopen this issue if you continue to have errors with dependencies.

Thanks,
Lauren
