### ISSUE TITLE
Error when installing strainphlan

### ISSUE THREAD

**Issue by achitzan** [biobakery/homebrew-biobakery#13]
After successfully installing all dependencies, I get the following when trying to install strainphlan itself:

==> Installing biobakery/biobakery/strainphlan
Warning: Use bowtie2 instead of deprecated homebrew/science/bowtie2
Warning: Use bowtie2 instead of deprecated homebrew/science/bowtie2
Warning: Use bowtie2 instead of deprecated homebrew/science/bowtie2
Warning: Use bowtie2 instead of deprecated homebrew/science/bowtie2
Warning: Use bowtie2 instead of deprecated homebrew/science/bowtie2
==> Downloading http://huttenhower.sph.harvard.edu/metaphlan2_downloads/strainphlan-2.6.0.tar.gz
######################################################################## 100.0%
==> Downloading https://bitbucket.org/biobakery/metaphlan2/downloads/strainphlan_homebrew_counter.txt
==> Downloading from https://bbuseruploads.s3.amazonaws.com/3a01cee1-3a04-4efc-9fd1-2172c21956d9/downloads/b00b4953-42c8-4435-b2c5-07fe1436cdbc/strainphlan_homebrew_counter.txt?Signature=3%2ByD1%2BnZ%2FHWi
######################################################################## 100.0%
==> rm *counter.txt
==> Downloading https://github.com/stamatak/standard-RAxML/archive/v8.1.15.tar.gz
==> Downloading from https://codeload.github.com/stamatak/standard-RAxML/tar.gz/v8.1.15
######################################################################## 100.0%
==> make -f Makefile.gcc
==> make -f Makefile.PTHREADS.gcc
==> make -f Makefile.SSE3.PTHREADS.gcc
==> Downloading https://github.com/samtools/samtools/archive/0.1.19.tar.gz
==> Downloading from https://codeload.github.com/samtools/samtools/tar.gz/0.1.19
######################################################################## 100.0%
==> make
==> make -C bcftools
==> cp samtools bcftools/bcftools bcftools/vcfutils.pl /exports/sg/eddie/iti/groups/researchservices/achitzan/brew/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor/bin/
==> cp misc/maq2sam-long misc/maq2sam-short misc/md5fa misc/md5sum-lite misc/wgsim /exports/sg/eddie/iti/groups/researchservices/achitzan/brew/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor/bin/
==> Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.11.0.tar.gz
######################################################################## 100.0%
==> python2 -c import setuptools... --no-user-cfg install --prefix=/exports/sg/eddie/iti/groups/researchservices/achitzan/brew/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor --single-version-externally
==> Downloading https://pypi.python.org/packages/source/p/pandas/pandas-0.13.1.tar.gz
######################################################################## 100.0%
==> python2 -c import setuptools... --no-user-cfg install --prefix=/exports/sg/eddie/iti/groups/researchservices/achitzan/brew/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor --single-version-externally
Last 15 lines from /home/achitzan/.cache/Homebrew/Logs/strainphlan/10.python2:
  File "/exports/sg/eddie/iti/groups/researchservices/achitzan/brew/.linuxbrew/Cellar/python/2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1220, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/exports/sg/eddie/iti/groups/researchservices/achitzan/brew/.linuxbrew/Cellar/python/2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 440, in get_provider
    __import__(moduleOrReq)
  File "/exports/sg/eddie/iti/groups/researchservices/achitzan/brew/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/exports/sg/eddie/iti/groups/researchservices/achitzan/brew/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/exports/sg/eddie/iti/groups/researchservices/achitzan/brew/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/exports/sg/eddie/iti/groups/researchservices/achitzan/brew/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/exports/sg/eddie/iti/groups/researchservices/achitzan/brew/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: libtatlas.so.3: cannot open shared object file: No such file or directory

If lbtatlas is a dependency, I don't understand why brew didn't install it. Please help!

**Comment by achitzan** [comment]
Update on this: libtatlas.so.3 actually exists on my system already, so not sure why brew is not finding it. any ideas?

thanks

**Comment by ljmciver** [comment]
Hello - I am not sure why brew is unable to find the libraries. What OS are you running on? We host a docker image of strainphlan if that would be useful.

Thank you,
Lauren

**Comment by d-yarmosh** [comment]
I'm receiving this error as well, using CentOS 7.

**Comment by ljmciver** [comment]
Hello - I added a new option to the strainphlan formula to install it without the python dependencies (eg numpy). To apply the option use "--without-dependencies". Then you can manually install numpy and possibly use the brew bottle if available for your OS instead of having to install from source with the command "brew install numpy". Alternatively we offer Docker images at dockerhub under the biobakery username. Please reopen this issue if you continue to have install errors and/or if you have any questions.

Thanks,
Lauren
