### ISSUE TITLE
homebrew/science is deprecated and unusable

### ISSUE THREAD

**Issue by draeath** [biobakery/homebrew-biobakery#16]
Many (edit: 5. workflows.rb, panphlan.rb, shortbred.rb, strainphlan.rb, metaphlan2.rb) formula in this repository have dependencies from homebrew/science. However, as-of Jan 1 that is no longer available. [See this PR for details.](https://github.com/Homebrew/homebrew-science/pull/6616)

**Comment by draeath** [comment]
I have also reported this [over at the biobakery project](https://bitbucket.org/biobakery/biobakery/issues/61), as I'm not sure which of the two locations is "best" for this report.

**Comment by ljmciver** [comment]
Hello - I did not know homebrew/science is no longer supported as of the beginning of this month. Thank you for posting this and bringing it to my attention. I will get the formulas updated. 

I will close the duplicate ticket in biobakery and keep this one open until the dependencies issue has been resolved.

Thanks,
Lauren

**Comment by draeath** [comment]
Hello Lauren, Has there been any progress on this by chance?

**Comment by ljmciver** [comment]
Hello - Yes, thanks for the ping! I have updated the formulas to pull dependencies from either homebrew/core or brewsci/science. Please let me know if you have any issues by reopening this ticket.

Thanks!
Lauren

**Comment by draeath** [comment]
Hello again! Thanks!

Quick related question. What are the chances of the dockerhub images being refreshed? Meanwhile, I'll try to see if I can get the biobakery/workflows:latest tag to point to the new locations and/or build the whole "chain" locally.
