### ISSUE TITLE
Change of links for blast downloads

### ISSUE THREAD

**Issue by mkweskin** [biobakery/homebrew-biobakery#17]
On my Mac curl is failing on downloading the blast executable in blast.rb for Macs: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.3.0/ncbi-blast-2.3.0+-universal-macosx.tar.gz

I believe the urls should now use https:// rather than ftp://

**Comment by ljmciver** [comment]
Hello - I tried it on linux and it works okay with ftp and also with https. I changed it to https (maybe it is Mac curl vs Linux curl?). Please edit this issue if this does not fix the error you are seeing.

Thanks,
Lauren

**Comment by mkweskin** [comment]
Thanks! Working on my Mac now. 👍

**Comment by ljmciver** [comment]
Fantastic! Thanks for closing loop and posting it is working. Please let me know if you have any other issues.
