### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by SK-N-BE** [biobakery/homebrew-biobakery#20]
Hei,
to install metaphlan2, I was using the command 

$ brew tap biobakery/biobakery
followed by
$ brew install metaphlan2

everything seems to work correctly; but at the end , I get the following error messages:

Last 15 lines from /home/SKNBE/.cache/Homebrew/Logs/metaphlan2/02.python2:
gcc-7: build/src.linux-x86_64-2.7/numpy/core/src/multiarray/nditer_templ.c
gcc-7: numpy/core/src/multiarray/python_xerbla.c
gcc-7: numpy/core/src/multiarray/ucsnarrow.c
gcc-7: build/src.linux-x86_64-2.7/numpy/core/src/multiarray/einsum.c
gcc-7: numpy/core/src/multiarray/number.c
gcc-7: numpy/core/src/multiarray/numpyos.c
numpy/core/src/multiarray/numpyos.c:18:10: fatal error: xlocale.h: No such file or directory
 #include <xlocale.h>

compilation terminated.
numpy/core/src/multiarray/numpyos.c:18:10: fatal error: xlocale.h: No such file or directory
 #include <xlocale.h>

compilation terminated.
error: Command "gcc-7 -fno-strict-aliasing -g -O2 -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=1 -DHAVE_CBLAS -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-x86_64-2.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/opt/openssl/include -I/home/linuxbrew/.linuxbrew/opt/sqlite/include -I/home/linuxbrew/.linuxbrew/opt/python@2/include/python2.7 -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -c numpy/core/src/multiarray/numpyos.c -o build/temp.linux-x86_64-2.7/numpy/core/src/multiarray/numpyos.o" failed with exit status 1

**Comment by ljmciver** [comment]
Hello - It looks like the error is from trying to install numpy (a dependency of metaphlan2). If you try installing metaphlan2 again, adding the option "--without-dependencies" it will bypass the numpy install. This should resolve the error you are seeing. Then install numpy with "brew install numpy". This way you can use a pre-complied bottle if available for your OS instead of having to install numpy from source. Please reopen this ticket if you have any issues.

Thanks,
Lauren

**Comment by SK-N-BE** [comment]
Thank you Lauren!
