### ISSUE TITLE
Problems installing lefse using brew

### ISSUE THREAD

**Issue by cjfields** [biobakery/homebrew-biobakery#23]
I'm attempting to install `lefse` on Mac OS X 10.13, using the instructions on the biobakery README using `brew` but have run into similar failures noted in past bug reports.  I am now trying to install using the recommended `--without-dependencies` flag, but I now see this:

```bash
$ brew install lefse --without-dependencies
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Installing lefse from biobakery/biobakery
==> Downloading https://bitbucket.org/nsegata/lefse/get/e3cabe93a0d1.tar.gz
Already downloaded: /Users/cjfields/Library/Caches/Homebrew/lefse-1.0.0-dev-e3cabe9.tar.gz
==> R -q -e install.packages('splines', lib='/usr/local/Cellar/lefse/1.0.0-dev-e3cabe9/libexec/R/library', repos='http://cran.r-project.org')
Last 15 lines from /Users/cjfields/Library/Logs/Homebrew/lefse/01.R:
2018-05-12 11:10:25 -0500

R
-q
-e
install.packages('splines', lib='/usr/local/Cellar/lefse/1.0.0-dev-e3cabe9/libexec/R/library', repos='http://cran.r-project.org')


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/biobakery/homebrew-biobakery/issues
```

It seems the `brew` installation is really finicky on Mac, should we switch to the bioconda installation?

**Comment by zburcham** [comment]
Hi @ljmciver , this may be a dumb question, but how do we actually run the programs in the docker images? For example, I tried "docker run biobakery/lefse format_input.py hmp_aerobiosis_small.txt hmp_aerobiosis_small.in -c 1 -s 2 -u 3 -o 1000000" in my command line but it just tells me that hmp_aerobiosis_small.txt does not exist even though I clearly have it in my working directory. Is there some sort of subcommand I need to use to run it?

**Comment by ljmciver** [comment]
Hi @zburcham , Totally not a dumb question! We should add more notes on our wiki about the docker images. You could run it with a shell ($ docker run -it biobakery_workflows bash). This would give you an interactive terminal or you could just run it directly (like you have). You would just need to add a volume from your home directory to your container (so it can find your file) (use --mount or -v).

Thanks,
Lauren

**Comment by zburcham** [comment]
Hi @ljmciver , thank you for the quick response. I guess I am just having some confusion with the whole docker thing. I tried install the biobakery/workflows and got this error: 

==> Downloading https://homebrew.bintray.com/bottles-science/ea-utils-1.1.2-806_2.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "ea-utils"
Download failed: https://homebrew.bintray.com/bottles-science/ea-utils-1.1.2-806_2.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://drive.google.com/uc?export=download&id=0B7KhouP0YeRAc2xackxzRnFrUEU
==> Downloading from https://doc-04-5g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/pdmgofev7k8nc8kbu
######################################################################## 100.0%
==> Patching
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/sparsehash-2.0.2/src/sparsehash/internal/sparsehashtable.h b/sparsehash-2.0.2/src/sparsehash/internal/sparsehashtable.h
|index 7ee1391..f54ea51 100644
|--- a/sparsehash-2.0.2/src/sparsehash/internal/sparsehashtable.h
|+++ b/sparsehash-2.0.2/src/sparsehash/internal/sparsehashtable.h
--------------------------
No file to patch.  Skipping patch.
3 out of 3 hunks ignored
can't find file to patch at input line 37
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|
|diff --git a/sparsehash-2.0.2/src/hashtable_test.cc b/sparsehash-2.0.2/src/hashtable_test.cc
|index 21c60a7..ede7c65 100644
|--- a/sparsehash-2.0.2/src/hashtable_test.cc
|+++ b/sparsehash-2.0.2/src/hashtable_test.cc
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Error: Failure while executing; `patch -g 0 -f -p1` exited with 1. Here's the output:
2181


And when I just try to run the lefse directly I can't seem to figure out how to create a mount/volume to a home directory.

**Comment by ljmciver** [comment]
@zburcham It looks like that error is from homebrew? Can you provide the docker commands you are running?

Thanks!
Lauren
