### ISSUE TITLE
Failed to install GraPhlAn  on Mac OS 

### ISSUE THREAD

**Issue by Hydro3639** [biobakery/homebrew-biobakery#24]
When I try to install GarPhlAn on my MacOS Sierra system, version 10.12.6, following this command, 
$ brew tap biobakery/biobakery
$ brew install graphlan
Here are the errors
=================================================================
==> Installing graphlan from biobakery/biobakery
==> Downloading https://bitbucket.org/nsegata/graphlan/get/d2ec14e3f75c.tar.gz
Already downloaded: /Users/Bubble/Library/Caches/Homebrew/graphlan-0.9.7.tar.gz
==> Downloading https://bitbucket.org/cibiocm/export2graphlan/get/b2e0ba667186.tar.gz
Already downloaded: /Users/Bubble/Library/Caches/Homebrew/graphlan--export2graphlan-667186.tar.gz
==> Downloading https://bitbucket.org/nsegata/hclust2/get/277c0d6a1d52.tar.gz
Already downloaded: /Users/Bubble/Library/Caches/Homebrew/graphlan--hclust2-52.tar.gz
==> mkdir /usr/local/Cellar/graphlan/0.9.7/libexec/hclust2
==> mv /usr/local/Cellar/graphlan/0.9.7/libexec/*.py /usr/local/Cellar/graphlan/0.9.7/libexec/hclust2/
==> Downloading https://bitbucket.org/nsegata/pyphlan/get/eae40ebc0030.tar.gz
Already downloaded: /Users/Bubble/Library/Caches/Homebrew/graphlan--pyphlan-0030.tar.gz
==> mkdir /usr/local/Cellar/graphlan/0.9.7/libexec/pyphlan
==> mv /usr/local/Cellar/graphlan/0.9.7/libexec/*.py /usr/local/Cellar/graphlan/0.9.7/libexec/pyphlan/
==> Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.11.0.tar.gz
Already downloaded: /Users/Bubble/Library/Caches/Homebrew/graphlan--numpy-1.11.0.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/graphlan/0.9.7/libexec --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/Bubble/Library/Logs/Homebrew/graphlan/05.python2:
2018-05-13 14:34:41 +0800

python2
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/graphlan/0.9.7/libexec
--single-version-externally-managed
--record=installed.txt

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/biobakery/homebrew-biobakery/issues

================================================

Besides, the default python version is 2.7.14. So is there anyone can help me to solve this problem, appreciate your time.

**Comment by ljmciver** [comment]
Hello - Can you check and see if you have a python2 executable? If so, you might be having issues installing the graphlan dependency numpy from source. You could try installing graphlan with the new option "--without-numpy" as this should resolve the error you are seeing trying to compile numpy. Then install numpy with a different package manager. Please reopen this ticket if you have additional issues or any questions.

Thanks,
Lauren
