### ISSUE TITLE
Provide option to skip counter for less public network areas.

### ISSUE THREAD

**Issue by galaxy001** [biobakery/homebrew-biobakery#25]
Hi, I'm here to report that the counter url `https://bitbucket.org/biobakery/metaphlan2/downloads/metaphlan2_homebrew_counter.txt` is being blocked by the China goverment. This means all computers in China cannot install `metaphlan2` directly from homebrew.

Would do please provide an option to skip downloading from `https://bitbucket.org` ?

**Comment by ljmciver** [comment]
Hi - If I change the URL to http would this work for you? Or are all bitbucket URLs blocked?

Thanks!
Lauren

**Comment by galaxy001** [comment]
`http://bitbucket.org` will 301 redirect to `https://bitbucket.org` thus useless.

The host `bbuseruploads.s3.amazonaws.com|54.231.82.106|:443` is blocked by China.

However, port 80 of bbuseruploads.s3.amazonaws.com is OK.

Which means, `http://bbuseruploads.s3.amazonaws.com/3a01cee1-3a04-4efc-9fd1-2172c21956d9/downloads/04610be4-fb93-49ce-8542-bd479b7c43e8/metaphlan2_homebrew_counter.txt?Signature=Km0***` works.

**Comment by ljmciver** [comment]
Hello, If you would install with conda or docker I think this should resolve the download issue that you are having. See the wiki for the instructions: https://bitbucket.org/biobakery/biobakery/wiki/biobakery_wiki .

Thanks,
Lauren
