### ISSUE TITLE
hclust2 install Error:SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

### ISSUE THREAD

**Issue by sanwen001** [biobakery/homebrew-biobakery#27]
I have three python version in ubuntu, 2.7\3.5\3.6
when I use command: `brew install hclust2`
![image](https://user-images.githubusercontent.com/21232606/42503101-5fead516-846a-11e8-81fb-c70fdf630457.png)
so I execute: `sudo apt-get install python-dev`
but show 
python-dev is already the newest version

**Comment by ffineis** [comment]
Same problem, just during the biobake install. Also attempted remedying by installing python-dev, python3-dev, gcc, build-essential, libssl-dev, but to no avail.

<img width="724" alt="screen shot 2018-07-31 at 4 57 23 pm" src="https://user-images.githubusercontent.com/11701129/43492299-f15d64d0-94ed-11e8-9c11-5fa0ea30d254.png">

**Comment by ljmciver** [comment]
Hi - Sorry you are having issues installing the numpy dependency. I wonder if homebrew also installed a python for you and that python is not able to find the development libraries you installed. I would recommend trying to install the homebrew formula with the flag "--without-numpy" and install numpy with apt-get. Ideally install numpy v1.11.0 which should work with most of the tools. Please reopen this issue if you continue to have errors or if you have any questions.

Thanks,
Lauren
