### ISSUE TITLE
Install issue with starainphlan

### ISSUE THREAD

**Issue by hkoo877** [biobakery/homebrew-biobakery#29]
Hello, I have been really trying to install strainphlan on my MAC and it kept giving me an error message. 

Please note my system below:
>python --version: 
Python 2.7.15
>brew link python
Error: No such keg: /usr/local/Cellar/python
>brew link python2
Warning: Already linked: /usr/local/Cellar/python@2/2.7.15_1
_______________________________________________________________________________________________________
Last 15 lines from /Users/myname/Library/Logs/Homebrew/strainphlan/10.python2:
customize IBMFCompiler
Could not locate executable xlf90
Could not locate executable xlf
customize IntelFCompiler
Could not locate executable ifort
Could not locate executable ifc
customize GnuFCompiler
Could not locate executable g77
customize G95FCompiler
Could not locate executable g95
customize PGroupFCompiler
Could not locate executable pgfortran
don't know how to compile Fortran code on platform 'posix'
building 'dfftpack' library
error: library dfftpack has Fortran sources but no Fortran compiler found
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:719:in `build'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:311:in `install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:321:in `install_formula'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
_______________________________________________________________________________________________________
I have been really trying to download the strainphaln using all kinds of methods (including docker and install using --without-dependencies), but nothing giving me any luck. Could you please help me to resolve this issue? Thanks.

**Comment by ljmciver** [comment]
Hello, Sorry you are having issues installing strainphlan with homebrew. Would installing with conda work for you? See the wiki for the instructions: https://bitbucket.org/biobakery/biobakery/wiki/biobakery_wiki . If you have any issues with conda please post to the biobakery conda recipe repo. We are moving away from homebrew and now supporting conda and docker.

Thanks,
Lauren
