### ISSUE TITLE
error in brew install

### ISSUE THREAD

**Issue by Francesca87** [biobakery/homebrew-biobakery#3]
I'm trying to install a software through home-brew, but I'm getting the error below.
I already tried to update brew and pip and to install gcc.

brew install strainphlan

....
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/strainphlan/2.5.0-6462147/libexec/vendor --single-version-exter
Last 15 lines from /Users/francescadefilippis/Library/Logs/Homebrew/strainphlan/11.python:
customize IBMFCompiler
Could not locate executable xlf90
Could not locate executable xlf
customize IntelFCompiler
Could not locate executable ifort
Could not locate executable ifc
customize GnuFCompiler
Could not locate executable g77
customize G95FCompiler
Could not locate executable g95
customize PGroupFCompiler
Could not locate executable pgfortran
don't know how to compile Fortran code on platform 'posix'
building 'dfftpack' library
error: library dfftpack has Fortran sources but no Fortran compiler found

**Comment by ljmciver** [comment]
The strainphlan formula installs dependencies from source including scipy which I believe requires a fortran compiler. It looks like the fortran compiler on your machine can not be found. Can you try installing gcc again?

**Comment by Francesca87** [comment]
I installed gcc but it gave the same error....

**Comment by Francesca87** [comment]
Is there any way to install the the fortran compiler  alone??

**Comment by ljmciver** [comment]
I believe you can install just the fortran binaries. Which platform are you running on? It looks like from the paths in your error messages you are on a Mac OS. Are you installing gcc with homebrew or XCode?

**Comment by Francesca87** [comment]
It's a MacOS Sierra 10.12 and I installed gcc with homebrew...

**Comment by ljmciver** [comment]
Do you have xcode installed on your MacOS? If so, have you tried installing the command line tools through xcode? This will install the compilers. My suggestion would be to install through xcode and remove the gcc homebrew install. I think this might fix it.

**Comment by Francesca87** [comment]
I tried to uninstall gcc and then install the command line tools via Xcode, but still getting the same error when installing strainphlan....
