### ISSUE TITLE
issues with install bio bakery

### ISSUE THREAD

**Issue by wmcjrlee** [biobakery/homebrew-biobakery#30]
Similar to last comment about strainphlan installation, I used home-brew and have had the same problem. 

python2 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Ce
Last 15 lines from /Users/wmcjrlee/Library/Logs/Homebrew/strainphlan/10.python2:
customize IBMFCompiler
Could not locate executable xlf90
Could not locate executable xlf
customize IntelFCompiler
Could not locate executable ifort
Could not locate executable ifc
customize GnuFCompiler
Could not locate executable g77
customize G95FCompiler
Could not locate executable g95
customize PGroupFCompiler
Could not locate executable pgfortran
don't know how to compile Fortran code on platform 'posix'
building 'dfftpack' library
error: library dfftpack has Fortran sources but no Fortran compiler found

How can I get around this?

**Comment by ljmciver** [comment]
Hello, Sorry you are having issues installing strainphlan with homebrew. Would installing with conda work for you? See the wiki for the instructions: https://bitbucket.org/biobakery/biobakery/wiki/biobakery_wiki . If you have any issues with conda please post to the biobakery conda recipe repo. We are moving away from homebrew and now supporting conda and docker. 

Thanks,
Lauren
