### ISSUE TITLE
Problem with brew install metaphlan2

### ISSUE THREAD

**Issue by ankit4035** [biobakery/homebrew-biobakery#33]
HI,

I am installing complete biobakery tool suite using brew. I am encountering problem while installing metaphlan2. Brew is downloading metaphlan2 archive from "http://huttenhower.sph.harvard.edu/metaphlan2_downloads/metaphlan2-2.6.0.tar.gz".

However, this link is not active and hence brew install command stucks. I have verified the link by checking it in browser, but it is dead. 
Also, the link of metaphlan2 is dead "http://huttenhower.sph.harvard.edu/metaphlan2".

**Comment by ljmciver** [comment]
Hello, Sorry you were having an issue with the link. Our site must have been down temporarily. It should be up now. Please try again. Also please note we are moving away from homebrew and now supporting conda and docker. Please try the other two installation methods if they might work for you.

Thanks,
Lauren
