### ISSUE TITLE
brew install breadcrumbs

### ISSUE THREAD

**Issue by konauday** [biobakery/homebrew-biobakery#36]
[server ~]$brew install breadcrumbs
Updating Homebrew...
==> Installing breadcrumbs from biobakery/biobakery
==> Installing dependencies for biobakery/biobakery/breadcrumbs: sqlite
==> Installing biobakery/biobakery/breadcrumbs dependency: sqlite
==> Downloading https://linuxbrew.bintray.com/bottles/sqlite-3.28.0.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/35/352c75c01430b2b66a7922175009a1f0fbf3c83b9908eb9a1af362477b6221e2?__gda__=exp=1555932616~hmac=342
######################################################################## 100.0%
==> Pouring sqlite-3.28.0.x86_64_linux.bottle.tar.gz
🍺  /data/marshpc/apps/biobakery/brew/linuxbrew/Cellar/sqlite/3.28.0: 13 files, 4.5MB
==> Installing biobakery/biobakery/breadcrumbs
==> Downloading https://bitbucket.org/biobakery/breadcrumbs/downloads/breadcrumbs-v0.92.tar.gz
Already downloaded: /home/users/hpcmgr/.cache/Homebrew/downloads/dade2d261a07445a5beaf22cb4ca390d1e669a2891b97b5fb914d3aa9d013930--breadcrumbs-v0.92.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.7.1.tar.gz
Already downloaded: /home/users/hpcmgr/.cache/Homebrew/downloads/32246c557b05158cfbb1b88f4aa555c35a721709caa7c670e99fe38e923a59fc--numpy-1.7.1.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/data/marshpc/apps/biobakery/brew/linuxbrew/Cellar/breadcrumbs/0.92/libexec --in
==> Downloading https://pypi.python.org/packages/source/s/scipy/scipy-0.12.0.tar.gz
Already downloaded: /home/users/hpcmgr/.cache/Homebrew/downloads/9957d16b3f57d822d8b05f6f90017aabbdbfffca982b51fa9fbc241800f94282--scipy-0.12.0.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/data/marshpc/apps/biobakery/brew/linuxbrew/Cellar/breadcrumbs/0.92/libexec --in
Last 15 lines from /home/users/hpcmgr/.cache/Homebrew/Logs/breadcrumbs/02.python2:
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/data/marshpc/apps/biobakery/brew/linuxbrew/Cellar/breadcrumbs/0.92/libexec
--install-scripts=/data/marshpc/apps/biobakery/brew/linuxbrew/Cellar/breadcrumbs/0.92/libexec/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "setup.py", line 165, in <module>
    setup_package()
  File "setup.py", line 145, in setup_package
    from numpy.distutils.core import setup
ImportError: No module named numpy.distutils.core

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/biobakery/homebrew-biobakery/issues

**Comment by konauday** [comment]
Can you please help me to sort out problem?

**Comment by konauday** [comment]
[hpcmgr@hpcnode05 ~]$brew install breadcrumbs
Updating Homebrew...
==> Installing breadcrumbs from biobakery/biobakery
==> Installing dependencies for biobakery/biobakery/breadcrumbs: sqlite
==> Installing biobakery/biobakery/breadcrumbs dependency: sqlite
==> Downloading https://linuxbrew.bintray.com/bottles/sqlite-3.28.0.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/35/352c75c01430b2b66a7922175009a1f0fbf3c83b9908eb9a1af362477b6221e2?__gda__=exp=1555932616~hmac=342
######################################################################## 100.0%
==> Pouring sqlite-3.28.0.x86_64_linux.bottle.tar.gz
🍺  /data/marshpc/apps/biobakery/brew/linuxbrew/Cellar/sqlite/3.28.0: 13 files, 4.5MB
==> Installing biobakery/biobakery/breadcrumbs
==> Downloading https://bitbucket.org/biobakery/breadcrumbs/downloads/breadcrumbs-v0.92.tar.gz
Already downloaded: /home/users/hpcmgr/.cache/Homebrew/downloads/dade2d261a07445a5beaf22cb4ca390d1e669a2891b97b5fb914d3aa9d013930--breadcrumbs-v0.92.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.7.1.tar.gz
Already downloaded: /home/users/hpcmgr/.cache/Homebrew/downloads/32246c557b05158cfbb1b88f4aa555c35a721709caa7c670e99fe38e923a59fc--numpy-1.7.1.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/data/marshpc/apps/biobakery/brew/linuxbrew/Cellar/breadcrumbs/0.92/libexec --in
==> Downloading https://pypi.python.org/packages/source/s/scipy/scipy-0.12.0.tar.gz
Already downloaded: /home/users/hpcmgr/.cache/Homebrew/downloads/9957d16b3f57d822d8b05f6f90017aabbdbfffca982b51fa9fbc241800f94282--scipy-0.12.0.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/data/marshpc/apps/biobakery/brew/linuxbrew/Cellar/breadcrumbs/0.92/libexec --in
Last 15 lines from /home/users/hpcmgr/.cache/Homebrew/Logs/breadcrumbs/02.python2:
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/data/marshpc/apps/biobakery/brew/linuxbrew/Cellar/breadcrumbs/0.92/libexec
--install-scripts=/data/marshpc/apps/biobakery/brew/linuxbrew/Cellar/breadcrumbs/0.92/libexec/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "setup.py", line 165, in <module>
    setup_package()
  File "setup.py", line 145, in setup_package
    from numpy.distutils.core import setup
ImportError: No module named numpy.distutils.core

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/biobakery/homebrew-biobakery/issues

**Comment by ljmciver** [comment]
Hello, Sorry you are having issues installing breadcrumbs with homebrew. Would you consider installing it with conda? See the wiki for the instructions: https://bitbucket.org/biobakery/biobakery/wiki/biobakery_wiki . If you have any issues with conda please post to the biobakery conda recipe repo. We are moving away from homebrew and now supporting conda and docker. 

Thanks,
Lauren
