### ISSUE TITLE
Issue with LEfSe installation

### ISSUE THREAD

**Issue by Altemani** [biobakery/homebrew-biobakery#37]
Hi, 

I am trying to install lefse on my mac but it give me this error:

brew install biobakery/biobakery/lefse
==> Installing lefse from biobakery/biobakery
==> Downloading https://bitbucket.org/nsegata/lefse/get/e3cabe93a0d1.tar.gz
Already downloaded: /Users/Faisal/Library/Caches/Homebrew/downloads/860fb6bb11236559bfa7d18011e886d06aa99f4210dda2e24876068236b9c1f1--nsegata-lefse-e3cabe93a0d1.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.11.0.tar.gz
Already downloaded: /Users/Faisal/Library/Caches/Homebrew/downloads/179cce20524ad92a21a0b3252a0f9d0e9138b63153280bf8e6900ef6a9972a8d--numpy-1.11.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/lefse/1.0.0-dev-e3cab
==> Downloading https://pypi.python.org/packages/source/m/matplotlib/matplotlib-1.5.1.tar.gz
Already downloaded: /Users/Faisal/Library/Caches/Homebrew/downloads/c6e0b40cfa64e5575033cb0251e797ef358bd9ef40ad024fa431ada84d1b8765--matplotlib-1.5.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/lefse/1.0.0-dev-e3cab
Last 15 lines from /Users/Faisal/Library/Logs/Homebrew/lefse/02.python:
                 cairo: no  [cairocffi or pycairo not found]
             windowing: no  [Microsoft Windows only]

OPTIONAL LATEX DEPENDENCIES
                dvipng: no
           ghostscript: no
                 latex: no
               pdftops: no

OPTIONAL PACKAGE DATA
                  dlls: no  [skipping due to configuration]

============================================================================
                        * The following required packages can not be built:
                        * freetype

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/biobakery/homebrew-biobakery/issues

---------------

I tried to install freetype by brew install freetype and try to reinstall lefse but I still get the same issue!

Any way to solve this issue?

Thanks,

**Comment by just-greg** [comment]
@Altemani I've got the exact same issue.
I'm running Mojave(v10.14.4). I wonder if there are any unlisted dependencies required for installation? 
Have you had any luck with rectifying this error?

**Comment by ljmciver** [comment]
Hello, Sorry you are having issues installing lefse with homebrew. Would you consider installing it with Conda instead? See the wiki for the instructions: https://bitbucket.org/biobakery/biobakery/wiki/biobakery_wiki . If you have any issues with conda please post to the biobakery conda recipe repo. We are moving away from homebrew and now supporting conda and docker. 

Thanks,
Lauren
