### ISSUE TITLE
error in 'brew install biobakery_tool_suite'  in biobakery vagrant image

### ISSUE THREAD

**Issue by WatsonWoo** [biobakery/homebrew-biobakery#39]
when i download the vm box and build a image of biobakery tool suite, i met lots error.  first one is the homebrew install.   in the orign .sh script, there install linuxbrew by git  form github. but the last install command of brew is different.  i install the last brew in the vm box success. although this, i meet this error.  i have not a computer background,  i don't know how to fix this.
so, everyone, please help me.

vagrant@biobakery:~$ brew install biobakery_tool_suite
Updating Homebrew...
==> Installing biobakery_tool_suite from biobakery/biobakery
==> Installing dependencies for biobakery/biobakery/biobakery_tool_suite: biobakery/biobakery/maaslin, brewsci/bio/cd-hit, biobakery/biobakery/shortbred, biobakery/biobakery/sparsedossa, biobakery/biobakery/ppanini, biobakery/biobakery/lefse, biobakery/biobakery/graphlan, gsl, mpich, biobakery/biobakery/micropita, biobakery/biobakery/breadcrumbs, biobakery/biobakery/halla, biobakery/biobakery/hclust2, curl, htslib, homebrew/core/samtools, biobakery/biobakery/panphlan, argtable, brewsci/bio/clustal-omega, brewsci/science/ea-utils and biobakery/biobakery/workflows
==> Installing biobakery/biobakery/biobakery_tool_suite dependency: biobakery/biobakery
==> Downloading https://bitbucket.org/biobakery/maaslin/downloads/Maaslin_0.0.5.tar.gz
Already downloaded: /home/vagrant/.cache/Homebrew/downloads/4ec06b0d2772dacccb83c119f9d8a3713cc21982aec8c0b3fe509dcf8b17b275--Maaslin_0.0.5.tar.gz
==> Downloading https://pypi.python.org/packages/source/b/blist/blist-1.3.6.tar.gz
Already downloaded: /home/vagrant/.cache/Homebrew/downloads/cdf77dd62b0f649ae008841e9f0ca0280a93a6cd9e63174be75e5736217d31dd--blist-1.3.6.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/home/linuxbrew/.linuxbre
==> R -q -e install.packages('foreach', lib='/home/linuxbrew/.linuxbrew/Cellar/maaslin/0.0.5
==> Downloading https://cran.r-project.org/src/contrib/Archive/gam/gam_1.14.tar.gz
Already downloaded: /home/vagrant/.cache/Homebrew/downloads/a6ff89450e1700acf081356ce47237ad4d1e6f84c246b2289d365057ebf6bfca--gam_1.14.tar.gz
==> R CMD INSTALL .
Last 15 lines from /home/vagrant/.cache/Homebrew/Logs/maaslin/03.R:
** libs
gfortran   -fpic  -g -O2 -fstack-protector-strong  -c backfit.f -o backfit.o
gfortran   -fpic  -g -O2 -fstack-protector-strong  -c backlo.f -o backlo.o
gfortran   -fpic  -g -O2 -fstack-protector-strong  -c bsplvd.f -o bsplvd.o
gfortran   -fpic  -g -O2 -fstack-protector-strong  -c bvalue.f -o bvalue.o
gfortran   -fpic  -g -O2 -fstack-protector-strong  -c bvalus.f -o bvalus.o
gfortran   -fpic  -g -O2 -fstack-protector-strong  -c linear.f -o linear.o
gfortran   -fpic  -g -O2 -fstack-protector-strong  -c lo.f -o lo.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c loessc.c -o loessc.o
loessc.c:43:15: fatal error: R.h: No such file or directory
compilation terminated.
/usr/lib/R/etc/Makeconf:159: recipe for target 'loessc.o' failed
make: *** [loessc.o] Error 1
ERROR: compilation failed for package ‘gam’
* removing ‘/home/linuxbrew/.linuxbrew/Cellar/maaslin/0.0.5/libexec/gam’

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/biobakery/homebrew-biobakery/issues

**Comment by ljmciver** [comment]
Hello, Sorry you are having issues installing the homebrew packages. The VM already has the tools pre-installed. If you would like to install the latest versions of the tools would you try the Conda packages? Please see the wiki for more information: https://bitbucket.org/biobakery/biobakery/wiki/biobakery_wiki . 

Thanks,
Lauren
