### ISSUE TITLE
Heat-map generation error

### ISSUE THREAD

**Issue by roshni-b** [biobakery/homebrew-biobakery#6]
```
/home/venkat/Desktop/Software/biobakery-metaphlan2-c3fb65390c21/utils/metaphla
n_hclust_heatmap.py --in merged_abundance_table.txt --out test.png
Traceback (most recent call last):
  File "/home/venkat/Desktop/Software/biobakery-metaphlan2-c3fb65390c21/utils/metaphlan_hclust_heatmap.py", line 481, in <module>
	tax_lev = pars['tax_lev']
  File "/home/venkat/Desktop/Software/biobakery-metaphlan2-c3fb65390c21/utils/metaphlan_hclust_heatmap.py", line 435, in hclust
	Y2 = sch.linkage(   Dt, method=method, metric=dist_func )
  File "/home/venkat/miniconda3/envs/python2/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 676, in linkage
	raise ValueError("The condensed distance matrix must contain only finite values.")
ValueError: The condensed distance matrix must contain only finite values.

```

**Comment by ljmciver** [comment]
Hello, Are you running a demo or a custom input file? Also what version of scipy are you using?

Thanks!
Lauren

**Comment by ljmciver** [comment]
Hello - It looks like you might be running a demo file. I tried the command with the demo tutorial file and I was not able to recreate your error message. My guess is you are using a different version of scipy or a different input file. I tested scipy 0.14.1 and 0.13.0. If you can change your scipy version it might resolve your error. Alternatively if you are not already, try running with the demo input file. It might be the contents of your input file that are causing the error. Please reopen this ticket if you continue to have issues.

Thanks,
Lauren
