### ISSUE TITLE
freetype dependency

### ISSUE THREAD

**Issue by Rav8024** [biobakery/homebrew-biobakery#7]
Hello,
my attempts to install metaphlan2 via linuxbrew constantly end up with:

"*The following required packages can not be built:
 * freetype"

Any ideas or help?

Thank you,
Ralf

**Comment by ljmciver** [comment]
Hello Ralf,

What is your operating system? Depending on your platform, you can try installing freetype with brew (ie "brew install freetype"). 

Thanks,
Lauren

**Comment by Rav8024** [comment]
Hi Lauren,

unfortunately, "brew install freetype" didn't help (My operating system is Ubuntu 16.04). In the code section I saw that some formulae have the comment "Remove use of brew freetype...". Seems to me as if there has been an issue with freetype. But anyway, the freetype problem remains in my case.

Thank you, 

Ralf

**Comment by ljmciver** [comment]
Hi Ralf - Yes, recent changes to the freetype formula cause it to no longer work on Ubuntu 16.04. In the past building the freetype formula from source worked but now it expects libraries that are not included. Do you have sudo/root permissions to install freetype as a package (ie "sudo apt-get libfreetype6-dev")? If not, we have a Docker image for metaphlan2 if you would like to use that instead.

Thanks,
Lauren

**Comment by ljmciver** [comment]
Hi Ralf - It looks like the freetype formula might now be fixed for ubuntu. I would recommend installing it from homebrew or as a package if you have permissions. Alternatively we have a Docker image for metaphlan2 if that would be preferable. 

Thanks!
Lauren
