### ISSUE TITLE
Error when installing biobakery with linuxbrew

### ISSUE THREAD

**Issue by shasan14** [biobakery/homebrew-biobakery#8]
I built linuxbrew and biobakery from scratch in my own account and got errors.  This server is running a recently updated RedHat Enterprise Linux 7.4
Linuxbrew and hello installed without issues:
Specifically I got errors when building strainphlan

Here is when I tried to install just strainphlan

[cgchildr@compile ~]$ brew install strainphlan
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Installing strainphlan from biobakery/biobakery
==> Downloading http://huttenhower.sph.harvard.edu/metaphlan2_downloads/strainphlan-2.6.0.tar.gz
Already downloaded: /home/cgchildr/.cache/Homebrew/strainphlan-2.6.0.tar.gz
==> Downloading https://bitbucket.org/biobakery/metaphlan2/downloads/strainphlan_homebrew_counter.txt
Already downloaded: /home/cgchildr/.cache/Homebrew/strainphlan--counter-homebrew.txt
==> rm *counter.txt
==> Downloading https://github.com/stamatak/standard-RAxML/archive/v8.1.15.tar.gz
Already downloaded: /home/cgchildr/.cache/Homebrew/strainphlan--raxml-8.1.15.tar.gz
==> make -f Makefile.gcc
==> make -f Makefile.PTHREADS.gcc
==> make -f Makefile.SSE3.PTHREADS.gcc
==> Downloading https://github.com/samtools/samtools/archive/0.1.19.tar.gz
Already downloaded: /home/cgchildr/.cache/Homebrew/strainphlan--samtools.v0.1.19-0.1.19.tar.gz
==> make
==> make -C bcftools
==> cp samtools bcftools/bcftools bcftools/vcfutils.pl /home/cgchildr/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor/bin/
==> cp misc/maq2sam-long misc/maq2sam-short misc/md5fa misc/md5sum-lite misc/wgsim /home/cgchildr/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor/bin/
==> Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.11.0.tar.gz
Already downloaded: /home/cgchildr/.cache/Homebrew/strainphlan--numpy-1.11.0.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/home/cgchildr/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor --single-version-external
==> Downloading https://pypi.python.org/packages/source/p/pandas/pandas-0.13.1.tar.gz
Already downloaded: /home/cgchildr/.cache/Homebrew/strainphlan--pandas-0.13.1.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/home/cgchildr/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor --single-version-external
==> Downloading https://pypi.python.org/packages/source/s/scipy/scipy-0.12.0.tar.gz
Already downloaded: /home/cgchildr/.cache/Homebrew/strainphlan--scipy-0.12.0.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/home/cgchildr/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor --single-version-external
Last 15 lines from /home/cgchildr/.cache/Homebrew/Logs/strainphlan/11.python2:
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://github.com/Homebrew/homebrew/issues> for instructions.
scipy/special/amos/zunhj.f:1:0:

       SUBROUTINE ZUNHJ(ZR, ZI, FNU, IPMTR, TOL, PHIR, PHII, ARGR, ARGI,
 ^
internal compiler error: Illegal instruction
0x7f6f413fc08f ???
        /tmp/glibc-20170905-4944-6pb7q1/glibc-2.23/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://github.com/Homebrew/homebrew/issues> for instructions.
error: Command "/home/cgchildr/.linuxbrew/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops -I/home/cgchildr/.linuxbrew/Cellar/strainphlan/2.6.0/libexec/vendor/lib64/python2.7/site-packages/numpy/core/include -c -c scipy/special/amos/zunhj.f -o build/temp.linux-x86_64-2.7/scipy/special/amos/zunhj.o" failed with exit status 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/biobakery/homebrew-biobakery/issues

**Comment by ljmciver** [comment]
Hello - It looks like the error is from the homebrew gfortran flags used when trying to compile scipy. I believe gfortran uses the default CFLAGS. You can run "$ brew --env" to check the flags. The "-O3" flag which applies optimizations appears to not be compatible with scipy. If the default includes the optimization flag I would change the flags with "$ export CFLAGS='new options'" (replacing 'new options' with the original flags minus the optimzation flag). I would then recommend re-installing homewbrew gfortran adding the option "--default-fortran-flags" to brew install (so it will use the CFLAGS options).

Alternatively, if you have root permissions on your machine or a container engine is installed we have a strainphlan Docker image that you can use.

Thanks!
Lauren
